/**
 * Mapeamento de cidades do Paraná para mesorregiões (uso em roteamento
 * de grupos WhatsApp regionais).
 *
 * Cobertura: ~150 principais municípios. Cidades não listadas caem em "OUTROS"
 * (admin pode ampliar a lista quando necessário).
 *
 * Normalização: acento + caixa removidos para match robusto contra
 * variações no banco (ex: "Curitiba", "CURITIBA", "Curítiba", " Curitiba ").
 */

export type PRRegion =
  | "RMC"
  | "LITORAL"
  | "NORTE"
  | "NOROESTE"
  | "OESTE"
  | "SUDOESTE"
  | "SUL"
  | "CENTRO"
  | "OUTROS";

function normalize(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .trim();
}

// Cada chave é o nome normalizado (sem acento, lowercase, trim)
const CITY_TO_REGION: Record<string, PRRegion> = {
  // ───── RMC — Região Metropolitana de Curitiba ─────
  "curitiba": "RMC",
  "sao jose dos pinhais": "RMC",
  "pinhais": "RMC",
  "colombo": "RMC",
  "araucaria": "RMC",
  "almirante tamandare": "RMC",
  "campo largo": "RMC",
  "fazenda rio grande": "RMC",
  "piraquara": "RMC",
  "campo magro": "RMC",
  "quatro barras": "RMC",
  "campina grande do sul": "RMC",
  "bocaiuva do sul": "RMC",
  "rio branco do sul": "RMC",
  "itaperucu": "RMC",
  "tunas do parana": "RMC",
  "cerro azul": "RMC",
  "lapa": "RMC",
  "balsa nova": "RMC",
  "contenda": "RMC",
  "mandirituba": "RMC",
  "tijucas do sul": "RMC",
  "agudos do sul": "RMC",
  "quitandinha": "RMC",
  "adrianopolis": "RMC",
  "dr ulysses": "RMC",
  "doutor ulysses": "RMC",

  // ───── LITORAL ─────
  "paranagua": "LITORAL",
  "pontal do parana": "LITORAL",
  "matinhos": "LITORAL",
  "guaratuba": "LITORAL",
  "antonina": "LITORAL",
  "morretes": "LITORAL",
  "guaraquecaba": "LITORAL",

  // ───── NORTE (Central + Pioneiro) ─────
  "londrina": "NORTE",
  "maringa": "NORTE",
  "cambe": "NORTE",
  "apucarana": "NORTE",
  "arapongas": "NORTE",
  "rolandia": "NORTE",
  "ibipora": "NORTE",
  "sarandi": "NORTE",
  "paicandu": "NORTE",
  "marialva": "NORTE",
  "mandaguari": "NORTE",
  "jandaia do sul": "NORTE",
  "califórnia": "NORTE",
  "california": "NORTE",
  "astorga": "NORTE",
  "colorado": "NORTE",
  "alvorada do sul": "NORTE",
  "bela vista do paraiso": "NORTE",
  "primeiro de maio": "NORTE",
  "sertanopolis": "NORTE",
  "tamarana": "NORTE",
  "jaguapita": "NORTE",
  "assai": "NORTE",
  "cornelio procopio": "NORTE",
  "santo antonio da platina": "NORTE",
  "jacarezinho": "NORTE",
  "wenceslau braz": "NORTE",
  "ourinhos": "NORTE",
  "ibaiti": "NORTE",
  "siqueira campos": "NORTE",
  "japira": "NORTE",
  "joaquim tavora": "NORTE",
  "carlopolis": "NORTE",
  "ribeirao claro": "NORTE",
  "tomazina": "NORTE",
  "sao jose da boa vista": "NORTE",
  "salto do itarare": "NORTE",
  "santana do itarare": "NORTE",
  "santo antonio do paraiso": "NORTE",
  "abatia": "NORTE",
  "andira": "NORTE",
  "barra do jacare": "NORTE",
  "cambara": "NORTE",
  "conselheiro mairinck": "NORTE",
  "figueira": "NORTE",
  "guapirama": "NORTE",
  "jaboti": "NORTE",
  "jundiai do sul": "NORTE",
  "nova america da colina": "NORTE",
  "nova fatima": "NORTE",
  "pinhalao": "NORTE",
  "quatigua": "NORTE",
  "ribeirao do pinhal": "NORTE",
  "santa amelia": "NORTE",
  "santa cecilia do pavao": "NORTE",
  "santa mariana": "NORTE",
  "sao jeronimo da serra": "NORTE",
  "uniflor": "NORTE",
  "urai": "NORTE",

  // ───── NOROESTE ─────
  "umuarama": "NOROESTE",
  "paranavai": "NOROESTE",
  "campo mourao": "NOROESTE",
  "cianorte": "NOROESTE",
  "goioere": "NOROESTE",
  "altonia": "NOROESTE",
  "icaraima": "NOROESTE",
  "ivate": "NOROESTE",
  "xambre": "NOROESTE",
  "tapejara": "NOROESTE",
  "tapira": "NOROESTE",
  "pero saraiva": "NOROESTE",
  "querencia do norte": "NOROESTE",
  "santa isabel do ivai": "NOROESTE",
  "diamante do norte": "NOROESTE",
  "santo antonio do caiua": "NOROESTE",
  "loanda": "NOROESTE",
  "marilena": "NOROESTE",
  "nova londrina": "NOROESTE",
  "alto paraiso": "NOROESTE",
  "porto rico": "NOROESTE",
  "amapora": "NOROESTE",
  "santa monica": "NOROESTE",
  "cidade gaucha": "NOROESTE",
  "guaporema": "NOROESTE",
  "indianopolis": "NOROESTE",
  "japura": "NOROESTE",
  "rondon": "NOROESTE",
  "sao tome": "NOROESTE",
  "tuneiras do oeste": "NOROESTE",

  // ───── OESTE ─────
  "cascavel": "OESTE",
  "toledo": "OESTE",
  "foz do iguacu": "OESTE",
  "marechal candido rondon": "OESTE",
  "guaira": "OESTE",
  "palotina": "OESTE",
  "assis chateaubriand": "OESTE",
  "santa helena": "OESTE",
  "medianeira": "OESTE",
  "matelandia": "OESTE",
  "santa terezinha de itaipu": "OESTE",
  "missal": "OESTE",
  "itaipulandia": "OESTE",
  "sao miguel do iguacu": "OESTE",
  "ramilandia": "OESTE",
  "vera cruz do oeste": "OESTE",
  "cafelandia": "OESTE",
  "corbelia": "OESTE",
  "santa tereza do oeste": "OESTE",
  "lindoeste": "OESTE",
  "santa lucia": "OESTE",
  "tres barras do parana": "OESTE",
  "capitao leonidas marques": "OESTE",
  "ouro verde do oeste": "OESTE",
  "diamante doeste": "OESTE",
  "diamante do oeste": "OESTE",
  "sao jose das palmeiras": "OESTE",
  "entre rios do oeste": "OESTE",
  "pato bragado": "OESTE",
  "mercedes": "OESTE",
  "quatro pontes": "OESTE",
  "ouro verde do iguacu": "OESTE",
  "boa vista da aparecida": "OESTE",
  "braganey": "OESTE",
  "iguatu": "OESTE",
  "jesuitas": "OESTE",
  "nova aurora": "OESTE",
  "formosa do oeste": "OESTE",
  "tupassi": "OESTE",
  "boa vista do sul": "OESTE",
  "iracema do oeste": "OESTE",
  "maripa": "OESTE",
  "nova santa rosa": "OESTE",
  "terra roxa": "OESTE",

  // ───── SUDOESTE ─────
  "pato branco": "SUDOESTE",
  "francisco beltrao": "SUDOESTE",
  "dois vizinhos": "SUDOESTE",
  "ampere": "SUDOESTE",
  "realeza": "SUDOESTE",
  "barracao": "SUDOESTE",
  "santa izabel do oeste": "SUDOESTE",
  "capanema": "SUDOESTE",
  "salgado filho": "SUDOESTE",
  "marmeleiro": "SUDOESTE",
  "renascenca": "SUDOESTE",
  "vitorino": "SUDOESTE",
  "marilena sw": "SUDOESTE",
  "clevelandia": "SUDOESTE",
  "chopinzinho": "SUDOESTE",
  "coronel vivida": "SUDOESTE",
  "honorio serpa": "SUDOESTE",
  "manfrinopolis": "SUDOESTE",
  "saudade do iguacu": "SUDOESTE",
  "salto do lontra": "SUDOESTE",
  "boa esperanca do iguacu": "SUDOESTE",
  "nova esperanca do sudoeste": "SUDOESTE",
  "santo antonio do sudoeste": "SUDOESTE",
  "pranchita": "SUDOESTE",
  "pinhal de sao bento": "SUDOESTE",
  "perola d oeste": "SUDOESTE",
  "perola doeste": "SUDOESTE",
  "planalto": "SUDOESTE",
  "bom sucesso do sul": "SUDOESTE",
  "bom jesus do sul": "SUDOESTE",
  "enéas marques": "SUDOESTE",
  "eneas marques": "SUDOESTE",
  "flor da serra do sul": "SUDOESTE",
  "itapejara doeste": "SUDOESTE",
  "itapejara do oeste": "SUDOESTE",
  "mariopolis": "SUDOESTE",
  "sulina": "SUDOESTE",
  "sao joao": "SUDOESTE",
  "sao jorge doeste": "SUDOESTE",
  "sao jorge do oeste": "SUDOESTE",
  "verê": "SUDOESTE",
  "vere": "SUDOESTE",
  "cruzeiro do iguacu": "SUDOESTE",

  // ───── SUL (Centro-Sul + Sudeste) ─────
  "guarapuava": "SUL",
  "uniao da vitoria": "SUL",
  "telemaco borba": "SUL",
  "irati": "SUL",
  "palmas": "SUL",
  "general carneiro": "SUL",
  "ortigueira": "SUL",
  "pinhao": "SUL",
  "candoi": "SUL",
  "campina do simao": "SUL",
  "espigao alto do iguacu": "SUL",
  "foz do jordao": "SUL",
  "porto barreiro": "SUL",
  "reserva do iguacu": "SUL",
  "turvo": "SUL",
  "marquinho": "SUL",
  "laranjeiras do sul": "SUL",
  "porto vitoria": "SUL",
  "bituruna": "SUL",
  "cruz machado": "SUL",
  "paulo frontin": "SUL",
  "antonio olinto": "SUL",
  "sao mateus do sul": "SUL",
  "rebouças": "SUL",
  "reboucas": "SUL",
  "fernandes pinheiro": "SUL",
  "imbituva": "SUL",
  "ipiranga": "SUL",
  "guamiranga": "SUL",
  "ivai": "SUL",
  "mallet": "SUL",
  "rio azul": "SUL",
  "teixeira soares": "SUL",
  "prudentopolis": "SUL",
  "imbau": "SUL",
  "ventania": "SUL",
  "tibagi": "SUL",
  "candido de abreu": "SUL",
  "manoel ribas": "SUL",

  // ───── CENTRO (Campos Gerais + Centro-Oriental) ─────
  "ponta grossa": "CENTRO",
  "castro": "CENTRO",
  "carambei": "CENTRO",
  "palmeira": "CENTRO",
  "porto amazonas": "CENTRO",
  "sao joao do triunfo": "CENTRO",
  "jaguariaiva": "CENTRO",
  "sengres": "CENTRO",
  "sengés": "CENTRO",
  "arapoti": "CENTRO",
  "pirai do sul": "CENTRO",
  "ipiranga centro": "CENTRO",
  "campo do tenente": "CENTRO",
};

/**
 * Resolve a região para uma cidade. Aceita variações de caixa/acento.
 * Retorna "OUTROS" quando city é null/vazia/não mapeada.
 */
export function regionForCity(city: string | null | undefined): PRRegion {
  if (!city) return "OUTROS";
  const key = normalize(city);
  if (!key) return "OUTROS";
  return CITY_TO_REGION[key] ?? "OUTROS";
}

export const PR_REGION_LABEL: Record<PRRegion, string> = {
  RMC: "RMC (Curitiba e Região)",
  LITORAL: "Litoral",
  NORTE: "Norte (Londrina/Maringá)",
  NOROESTE: "Noroeste (Umuarama/Paranavaí)",
  OESTE: "Oeste (Cascavel/Toledo/Foz)",
  SUDOESTE: "Sudoeste (Pato Branco/Beltrão)",
  SUL: "Sul (Guarapuava/União da Vitória)",
  CENTRO: "Campos Gerais (Ponta Grossa)",
  OUTROS: "Outros / não mapeada",
};
